# Generated by Django 2.2.14 on 2021-01-25 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tasks", "0010_auto_20201207_1818"),
    ]

    operations = [
        migrations.CreateModel(
            name="XentialTicket",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bptl_ticket_uuid",
                    models.UUIDField(
                        help_text="BPTL specific Xential ticket UUID",
                        verbose_name="BPTL ticket UUID",
                    ),
                ),
                (
                    "ticket_uuid",
                    models.UUIDField(
                        help_text="Xential ticket UUID",
                        verbose_name="Xential ticket UUID",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="tasks.BaseTask"
                    ),
                ),
            ],
            options={
                "verbose_name": "Xential Ticket",
                "verbose_name_plural": "Xential Tickets",
            },
        ),
    ]
