# Generated by Django 2.2.14 on 2021-02-05 13:49

import bptl.work_units.xential.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("xential", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="XentialConfiguration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "auth_key",
                    models.CharField(
                        default=bptl.work_units.xential.models.get_auth_key,
                        help_text="The unique authentication key for Xential API to authenticate itself whenreturning a newly built document.",
                        max_length=200,
                        verbose_name="authentication key",
                    ),
                ),
            ],
            options={
                "verbose_name": "Xential Configuration",
            },
        ),
    ]
