# Generated by Django 2.2.14 on 2021-02-03 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("xential", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="xentialticket",
            name="is_ticket_complete",
            field=models.BooleanField(
                default=False,
                help_text="Indicates whether the document was built in Xential.",
                verbose_name="Ticket complete",
            ),
        ),
    ]
