# Generated by Django 2.2.14 on 2021-02-16 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("xential", "0002_xentialconfiguration"),
        ("xential", "0002_xentialticket_is_ticket_complete"),
    ]

    operations = []
