# Generated by Django 2.2.14 on 2021-02-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("xential", "0003_merge_20210216_1036"),
    ]

    operations = [
        migrations.AddField(
            model_name="xentialticket",
            name="document_uuid",
            field=models.CharField(
                max_length=200,
                blank=True,
                default="",
                help_text="UUID of the document associated with the ticket",
                verbose_name="Document UUID",
            ),
        ),
    ]
