# Generated by Django 2.2.14 on 2021-02-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("xential", "0004_xentialticket_document_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="xentialticket",
            name="document_uuid",
            field=models.UUIDField(
                blank=True,
                default=None,
                help_text="UUID of the document associated with the ticket",
                null=True,
                verbose_name="Document UUID",
            ),
        ),
    ]
