# Generated by Django 2.2.24 on 2021-09-24 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("xential", "0005_auto_20210222_1706"),
    ]

    operations = [
        migrations.AlterField(
            model_name="xentialticket",
            name="document_uuid",
            field=models.UUIDField(
                default=None,
                help_text="UUID of the document associated with the ticket",
                null=True,
                verbose_name="Document UUID",
            ),
        ),
    ]
