# Generated by Django 2.2.14 on 2020-11-02 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("zgw_consumers", "0009_auto_20200401_0829"),
        ("brp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="brpconfig",
            name="service",
            field=models.ForeignKey(
                limit_choices_to={"api_type": "orc"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="zgw_consumers.Service",
                verbose_name="service",
                help_text="Configurations for the client that makes requests to the API.",
            ),
        ),
    ]
