# Generated by Django 2.2.14 on 2020-11-02 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("brp", "0003_auto_20201102_1057"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="brpconfig",
            name="api_root",
        ),
        migrations.RemoveField(
            model_name="brpconfig",
            name="header_key",
        ),
        migrations.RemoveField(
            model_name="brpconfig",
            name="header_value",
        ),
    ]
