# Generated by Django 2.2.9 on 2020-01-13 17:01

from django.db import migrations, models

import bptl.camunda.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FetchedTask",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "worker_id",
                    models.CharField(
                        default=bptl.camunda.models.get_worker_id,
                        help_text="The worker ID that picked up the task. Only the same worker ID is allowed to unlock/modify the task. Used as a lock.",
                        max_length=255,
                    ),
                ),
                (
                    "topic_name",
                    models.CharField(
                        help_text="External tasks get published to a certain topic. Topics determine which functions need to run for a task.",
                        max_length=255,
                        verbose_name="topic name",
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="priority"
                    ),
                ),
                ("task_id", models.CharField(max_length=50, verbose_name="task id")),
                (
                    "variables",
                    models.JSONField(default=dict),
                ),
            ],
            options={
                "verbose_name": "fetched task",
                "verbose_name_plural": "fetched tasks",
            },
        ),
    ]
