# Generated by Django 2.2.9 on 2020-02-10 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("camunda", "0004_auto_20200127_1701"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="FetchedTask",
            new_name="ExternalTask",
        ),
    ]
