# Generated by Django 2.2.9 on 2020-02-11 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("camunda", "0005_auto_20200210_1237"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="externaltask",
            options={
                "verbose_name": "external task",
                "verbose_name_plural": "external tasks",
            },
        ),
    ]
