# Generated by Django 2.2.9 on 2020-02-14 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camunda", "0006_auto_20200211_1716"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externaltask",
            name="topic_name",
            field=models.CharField(
                help_text="Topics determine which functions need to run for a task.",
                max_length=255,
                verbose_name="topic name",
            ),
        ),
    ]
