# Generated by Django 2.2.10 on 2020-02-21 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camunda", "0007_auto_20200214_1109"),
    ]

    operations = [
        migrations.AddField(
            model_name="externaltask",
            name="execution_error",
            field=models.TextField(
                blank=True,
                help_text="The error that occurred during execution.",
                verbose_name="execution error",
            ),
        ),
    ]
