# Generated by Django 2.2.10 on 2020-02-26 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("camunda", "0010_copy_tasks_to_parent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="externaltask",
            name="execution_error",
        ),
        migrations.RemoveField(
            model_name="externaltask",
            name="id",
        ),
        migrations.RemoveField(
            model_name="externaltask",
            name="result_variables",
        ),
        migrations.RemoveField(
            model_name="externaltask",
            name="status",
        ),
        migrations.RemoveField(
            model_name="externaltask",
            name="topic_name",
        ),
        migrations.RemoveField(
            model_name="externaltask",
            name="variables",
        ),
    ]
