# Generated by Django 2.2.24 on 2021-09-24 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camunda", "0014_externaltask_camunda_error"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externaltask",
            name="instance_id",
            field=models.CharField(max_length=50, verbose_name="process instance id"),
        ),
    ]
