# Generated by Django 3.2.12 on 2022-05-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CoreConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "non_adfs_login_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="A flag that allows non-ADFS login (True) or not (False).",
                        verbose_name="Non-ADFS login enabled",
                    ),
                ),
            ],
            options={
                "verbose_name": "global configuration",
            },
        ),
    ]
