# Generated by Django 3.2.12 on 2023-02-10 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("zgw_consumers", "0012_auto_20210104_1039"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="coreconfig",
            name="primary_objecttypes_api",
            field=models.ForeignKey(
                help_text="Default OBJECTTYPES API service to use",
                limit_choices_to={"api_type": "orc"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="zgw_consumers.service",
                verbose_name="Primary OBJECTTYPES API",
            ),
        ),
        migrations.AlterField(
            model_name="coreconfig",
            name="non_adfs_login_enabled",
            field=models.BooleanField(
                default=False,
                help_text="A flag that allows non-ADFS login (True) or not (False).",
                verbose_name="Non-ADFS login enabled",
            ),
        ),
    ]
