# Generated by Django 3.2.12 on 2025-10-15 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_auto_20230210_1625"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coreconfig",
            name="non_adfs_login_enabled",
        ),
        migrations.AddField(
            model_name="coreconfig",
            name="non_sso_login_enabled",
            field=models.BooleanField(
                default=False,
                help_text="A flag that allows non-SSO login (True) or not (False).",
                verbose_name="Non-SSO login enabled",
            ),
        ),
        migrations.AlterField(
            model_name="coreconfig",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
