# Generated by Django 2.2.9 on 2020-01-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskmapping",
            name="callback",
            field=models.CharField(
                help_text="Listener to connect to the topic. This is a specialized piece of code that will run for each task with the configured topic.",
                max_length=255,
                verbose_name="callback",
            ),
        ),
        migrations.AlterField(
            model_name="taskmapping",
            name="topic_name",
            field=models.CharField(
                help_text="Topic as defined in the Camunda External Task. Topics are used to decide which listener to run for a task.",
                max_length=255,
                unique=True,
                verbose_name="topic name",
            ),
        ),
    ]
