# Generated by Django 2.2.2 on 2019-07-01 15:01

from django.db import migrations


def rewrite_callback_paths(apps, schema_editor):
    TaskMapping = apps.get_model("tasks.TaskMapping")

    mappings = TaskMapping.objects.filter(
        callback__regex=r"^camunda_worker\.tasks\.tasks\.worker\.\w+$"
    )
    for mapping in mappings:
        path, name = mapping.callback.rsplit(".", 1)
        mapping.callback = ".".join(["bptl.work_units.zgw.tasks", name])
        mapping.save()


class Migration(migrations.Migration):

    dependencies = [("tasks", "0003_change_callback_path")]

    operations = [migrations.RunPython(rewrite_callback_paths)]
