# Generated by Django 2.2.9 on 2020-02-14 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_change_callback_path_after_big_rename"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskmapping",
            name="topic_name",
            field=models.CharField(
                help_text="Topic as defined in the Task of external Business Process engine. Topics are used to decide which listener to run for a task.",
                max_length=255,
                unique=True,
                verbose_name="topic name",
            ),
        ),
    ]
