# Generated by Django 2.2.10 on 2020-02-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zgw", "0001_initial"),
        ("zgw_consumers", "0004_auto_20200113_1728"),
        ("tasks", "0005_auto_20200214_1109"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskmapping",
            name="default_services",
            field=models.ManyToManyField(
                related_name="task_mappings",
                through="zgw.DefaultService",
                to="zgw_consumers.Service",
            ),
        ),
    ]
