# Generated by Django 2.2.10 on 2020-02-21 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("zgw_consumers", "0004_auto_20200113_1728"),
        ("tasks", "0005_auto_20200214_1109"),
    ]

    operations = [
        migrations.CreateModel(
            name="DefaultService",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alias",
                    models.CharField(
                        help_text="Alias for the service used in the particular task",
                        max_length=100,
                        verbose_name="alias",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="zgw_consumers.Service",
                    ),
                ),
                (
                    "task_mapping",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tasks.TaskMapping",
                    ),
                ),
            ],
            options={
                "verbose_name": "default service",
                "verbose_name_plural": "default services",
                "unique_together": {("task_mapping", "alias")},
            },
        ),
        migrations.AddField(
            model_name="taskmapping",
            name="default_services",
            field=models.ManyToManyField(
                related_name="task_mappings",
                through="tasks.DefaultService",
                to="zgw_consumers.Service",
            ),
        ),
    ]
