# Generated by Django 2.2.10 on 2020-02-21 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zgw_consumers", "0004_auto_20200113_1728"),
        ("tasks", "0006_auto_20200221_1552"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="defaultservice", unique_together={("task_mapping", "service")},
        ),
    ]
