# Generated by Django 2.2.14 on 2020-12-07 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0009_auto_20201207_1814"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="defaultservice",
            table=None,
        ),
    ]
