# Generated by Django 3.2.12 on 2025-08-14 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0012_taskmapping_engine_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskmapping",
            name="engine_type",
            field=models.CharField(
                choices=[
                    ("camunda", "Camunda"),
                    ("activiti", "Activiti"),
                    ("openklant", "OpenKlant"),
                    ("crontask", "CronTask"),
                ],
                default="camunda",
                help_text="The engine type used for the task.",
                max_length=50,
                verbose_name="engine_type",
            ),
        ),
    ]
