# Generated by Django 5.2.9 on 2025-12-29 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0015_alter_basetask_polymorphic_ctype"),
        (
            "zgw_consumers",
            "0027_service_oauth2_scope_service_oauth2_token_url_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="defaultservice",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="defaultservice",
            constraint=models.UniqueConstraint(
                fields=("task_mapping", "service"), name="unique_task_mapping_service"
            ),
        ),
        migrations.AddConstraint(
            model_name="defaultservice",
            constraint=models.UniqueConstraint(
                fields=("task_mapping", "alias"), name="unique_task_mapping_alias"
            ),
        ),
    ]
