# Generated by Django 2.2.9 on 2020-01-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("external_tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fetchedtask",
            name="lock_expires_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="lock expires at"
            ),
        ),
    ]
