# Generated by Django 2.2.9 on 2020-01-16 13:32

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("external_tasks", "0002_fetchedtask_lock_expires_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="fetchedtask",
            name="result_variables",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="fetchedtask",
            name="status",
            field=models.CharField(
                choices=[
                    ("initial", "Initial"),
                    ("in_progress", "In progress"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="initial",
                help_text="The current status of task processing",
                max_length=50,
                verbose_name="status",
            ),
        ),
    ]
