# Generated by Django 2.2.14 on 2020-10-23 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ZACConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "api_root",
                    models.URLField(
                        default="https://zac.example.com",
                        help_text="Root URL of ZAC api",
                        verbose_name="API-root",
                    ),
                ),
                (
                    "header_key",
                    models.CharField(
                        blank=True,
                        help_text="HTTP Authorization header name, required if the API is not open.",
                        max_length=100,
                        verbose_name="header key",
                    ),
                ),
                (
                    "header_value",
                    models.CharField(
                        blank=True,
                        help_text="HTTP Authorization header value, required if the API is not open.",
                        max_length=255,
                        verbose_name="header value",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zac Configuration",
            },
        ),
    ]
