# Generated by Django 2.2.14 on 2020-11-02 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zac", "0003_auto_20201102_1146"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="zacconfig",
            name="api_root",
        ),
        migrations.RemoveField(
            model_name="zacconfig",
            name="header_key",
        ),
        migrations.RemoveField(
            model_name="zacconfig",
            name="header_value",
        ),
    ]
