# Generated by Django 2.2.14 on 2020-12-07 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zac", "0005_move_zac_config_to_default_service"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ZACConfig",
        ),
    ]
