# Generated by Django 2.2.10 on 2020-02-24 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("zgw_consumers", "0004_auto_20200113_1728"),
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DefaultService",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alias",
                    models.CharField(
                        help_text="Alias for the service used in the particular task",
                        max_length=100,
                        verbose_name="alias",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="zgw_consumers.Service",
                    ),
                ),
                (
                    "task_mapping",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tasks.TaskMapping",
                    ),
                ),
            ],
            options={
                "verbose_name": "default service",
                "verbose_name_plural": "default services",
                "unique_together": {("task_mapping", "service")},
            },
        ),
    ]
