# Generated by Django 2.2.14 on 2020-12-07 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zgw", "0003_auto_20201112_1547"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="defaultservice",
            table="tasks_defaultservice",
        ),
    ]
