# Generated by Django 2.2.14 on 2020-12-07 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0009_auto_20201207_1814"),
        ("zgw", "0004_auto_20201207_1808"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="DefaultService",
                ),
            ]
        ),
    ]
