# Generated by Django 3.2.12 on 2023-06-23 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zgw", "0006_metaobjecttypesconfig"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MetaObjectTypesConfig",
        ),
    ]
