# Generated by Django 3.2.12 on 2025-08-13 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tasks", "0012_taskmapping_engine_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="CronTask",
            fields=[
                (
                    "basetask_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="tasks.basetask",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("tasks.basetask",),
        ),
    ]
