# Generated by Django 2.2.14 on 2020-08-21 15:17

from django.db import migrations, models

import bptl.work_units.valid_sign.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ValidSignConfiguration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "auth_key",
                    models.CharField(
                        default=bptl.work_units.valid_sign.models.get_auth_key,
                        help_text="The unique authentication key for ValidSign. This maps to the 'key' field in the callback creation (https://apidocs.validsign.nl/#operation/api.callback.post). You should fill in this key when you configure the callback URL in the dashboard.",
                        max_length=200,
                        verbose_name="authentication key",
                    ),
                ),
            ],
            options={"verbose_name": "ValidSign Configuration",},
        ),
    ]
