# Generated by Django 2.2.14 on 2020-08-21 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0008_auto_20200228_1616"),
        ("valid_sign", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CreatedPackage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "package_id",
                    models.CharField(
                        db_index=True, max_length=200, verbose_name="package ID"
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="tasks.BaseTask"
                    ),
                ),
            ],
            options={
                "verbose_name": "created package",
                "verbose_name_plural": "created packages",
            },
        ),
    ]
