# Generated by Django 2.2.14 on 2020-10-12 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("zgw_consumers", "0011_remove_service_extra"),
    ]

    operations = [
        migrations.CreateModel(
            name="App",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Human readable app identifier.",
                        max_length=100,
                        verbose_name="label",
                    ),
                ),
                (
                    "app_id",
                    models.CharField(
                        help_text="(Globally) unique application identifier. Typically the URL of the application in the Autorisaties API.",
                        max_length=1000,
                        unique=True,
                        verbose_name="app ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "application",
                "verbose_name_plural": "applications",
            },
        ),
        migrations.CreateModel(
            name="AppServiceCredentials",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_id", models.CharField(blank=True, max_length=255)),
                ("secret", models.CharField(blank=True, max_length=255)),
                (
                    "header_key",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="header key"
                    ),
                ),
                (
                    "header_value",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="header value"
                    ),
                ),
                (
                    "app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="credentials.App",
                        verbose_name="application",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        help_text="External service to configure credentials for.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="zgw_consumers.Service",
                        verbose_name="service",
                    ),
                ),
            ],
            options={
                "verbose_name": "service credentials",
                "verbose_name_plural": "service credentials",
            },
        ),
        migrations.AddConstraint(
            model_name="appservicecredentials",
            constraint=models.UniqueConstraint(
                fields=("app", "service"), name="unique_app_service"
            ),
        ),
    ]
