# Generated by Django 3.2.12 on 2023-06-23 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("objects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="metaobjecttypesconfig",
            name="checklist_objecttype",
            field=models.URLField(
                default="",
                help_text="A URL-reference to the Checklist OBJECTTYPE. This is used to fetch the checklist objecttype for a ZAAK.",
                verbose_name="URL-reference to Checklist in OBJECTTYPES API.",
            ),
        ),
        migrations.AddField(
            model_name="metaobjecttypesconfig",
            name="checklisttype_objecttype",
            field=models.URLField(
                default="",
                help_text="A URL-reference to the ChecklistType OBJECTTYPE. This is used to get the questions for a checklist for a ZAAKTYPE.",
                verbose_name="URL-reference to ChecklistType in OBJECTTYPES API.",
            ),
        ),
    ]
