# Generated by Django 3.2.12 on 2024-01-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("objects", "0002_auto_20230623_1626"),
    ]

    operations = [
        migrations.AddField(
            model_name="metaobjecttypesconfig",
            name="default",
            field=models.BooleanField(
                default=True,
                help_text="Setting to False will allow the user to define custom objecttypes instead of the URL-references retrieved from the list of meta objecttypes from the OBJECTS API.",
            ),
        ),
        migrations.AddField(
            model_name="metaobjecttypesconfig",
            name="meta_list_objecttype",
            field=models.URLField(
                default="",
                help_text="A URL-reference to the Meta List OBJECTTYPE. This is used to fetch the meta list objecttype for managing meta objects and objecttypes.",
                verbose_name="URL-reference to MetaListObjectType in OBJECTTYPES API.",
            ),
        ),
        migrations.AddField(
            model_name="metaobjecttypesconfig",
            name="oudbehandelaren_objecttype",
            field=models.URLField(
                default="",
                help_text="A URL-reference to the Oudbehandelaren OBJECTTYPE. This is used to register the old ROL when the ROL was of ROLTYPE `behandelaar`.",
                verbose_name="URL-reference to Oudbehandelaren in OBJECTTYPES API.",
            ),
        ),
        migrations.AddField(
            model_name="metaobjecttypesconfig",
            name="zaaktype_attribute_objecttype",
            field=models.URLField(
                default="",
                help_text="A URL-reference to the ZaaktypeAttributes OBJECTTYPE. This is used to get extra data for EIGENSCHAPs.",
                verbose_name="URL-reference to ZaaktypeAttributes in OBJECTTYPES API.",
            ),
        ),
    ]
