# Generated by Django 3.2.12 on 2025-03-24 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("zgw_consumers", "0012_auto_20210104_1039"),
        ("openklant", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="openklantconfig",
            name="actor",
            field=models.ForeignKey(
                help_text="Actor associated with BPTL in OpenKlant.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="openklant.openklantactormodel",
                verbose_name="OpenKlant Actor",
            ),
        ),
        migrations.AlterField(
            model_name="openklantconfig",
            name="service",
            field=models.ForeignKey(
                help_text="External service to configure credentials for.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="zgw_consumers.service",
                verbose_name="service",
            ),
        ),
    ]
