# Generated by Django 3.2.12 on 2025-04-04 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("zgw_consumers", "0012_auto_20210104_1039"),
        ("openklant", "0003_rename_task_uuid_openklantinternaltaskmodel_task_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="InterneTask",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gevraagde_handeling",
                    models.CharField(
                        default="",
                        help_text="Gevraagde handeling voor actor(en) van interne taak in OpenKlant.",
                        max_length=200,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Interne Tasks gevraagde handeling",
            },
        ),
        migrations.AddField(
            model_name="openklantconfig",
            name="objects_service",
            field=models.ForeignKey(
                help_text="External objects service used by OpenKlant.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="objects_service",
                to="zgw_consumers.service",
                verbose_name="objects service",
            ),
        ),
        migrations.AddField(
            model_name="openklantconfig",
            name="objecttypes_service",
            field=models.ForeignKey(
                help_text="External objecttypes service used by OpenKlant.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="objecttypes_service",
                to="zgw_consumers.service",
                verbose_name="objecttypes service",
            ),
        ),
    ]
