# Generated by Django 3.2.12 on 2025-06-02 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openklant', '0005_failedopenklanttasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='openklantconfig',
            name='debug',
            field=models.BooleanField(default=False, help_text='Enable debug mode for OpenKlant tasks.', verbose_name='debug mode'),
        ),
        migrations.AddField(
            model_name='openklantconfig',
            name='debug_email',
            field=models.EmailField(blank=True, help_text='Email address for debugging emails in OpenKlant.', max_length=254, null=True, verbose_name='debug email'),
        ),
        migrations.AddField(
            model_name='openklantconfig',
            name='logging_email',
            field=models.EmailField(blank=True, help_text='Email address for logging emails in OpenKlant.', max_length=254, null=True, verbose_name='logging email'),
        ),
    ]
