# Generated by Django 3.2.12 on 2025-06-11 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("openklant", "0007_kccemailconfig"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kccemailconfig",
            name="from_email",
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="kccemailconfig",
            name="host",
            field=models.CharField(
                blank=True, default="smtp.kcc.nl", max_length=254, null=True
            ),
        ),
        migrations.AlterField(
            model_name="kccemailconfig",
            name="username",
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
