# Generated by Django 3.2.12 on 2025-06-11 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("openklant", "0008_auto_20250611_0953"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kccemailconfig",
            name="port",
            field=models.PositiveIntegerField(default=587),
        ),
    ]
