# Generated by Django 2.2.9 on 2020-02-11 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ActivitiConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "root_url",
                    models.URLField(
                        default="https://activiti.utrechtproeftuin.nl/activiti-app/api/",
                        help_text="Root URL where activiti is installed. The REST api path is appended to this.",
                        verbose_name="camunda root",
                    ),
                ),
                (
                    "rest_api_path",
                    models.CharField(
                        default="management/engine",
                        max_length=255,
                        verbose_name="REST api path",
                    ),
                ),
                (
                    "auth_header",
                    models.TextField(
                        blank=True,
                        help_text="HTTP Authorization header value, required if the API is not open.",
                        verbose_name="authorization header",
                    ),
                ),
            ],
            options={"verbose_name": "Activiti configuration",},
        ),
    ]
