# Generated by Django 2.2.9 on 2020-02-11 16:16

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activiti", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceTask",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "topic_name",
                    models.CharField(
                        help_text="Topics determine which functions need to run for a task.",
                        max_length=255,
                        verbose_name="topic name",
                    ),
                ),
                (
                    "variables",
                    django.contrib.postgres.fields.jsonb.JSONField(default=dict),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initial", "Initial"),
                            ("in_progress", "In progress"),
                            (
                                "performed",
                                "The task is performed, but not sent to Camunda",
                            ),
                            ("failed", "Failed"),
                            ("completed", "Completed"),
                        ],
                        default="initial",
                        help_text="The current status of task processing",
                        max_length=50,
                        verbose_name="status",
                    ),
                ),
                (
                    "result_variables",
                    django.contrib.postgres.fields.jsonb.JSONField(default=dict),
                ),
            ],
        ),
    ]
