# Generated by Django 2.2.9 on 2020-02-14 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("activiti", "0002_servicetask"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="servicetask",
            options={
                "verbose_name": "aervice task",
                "verbose_name_plural": "service tasks",
            },
        ),
    ]
