# Generated by Django 2.2.9 on 2020-02-20 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activiti", "0003_auto_20200214_1109"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="servicetask",
            options={
                "verbose_name": "service task",
                "verbose_name_plural": "service tasks",
            },
        ),
        migrations.RemoveField(model_name="activiticonfig", name="rest_api_path",),
        migrations.AddField(
            model_name="activiticonfig",
            name="enterprise",
            field=models.BooleanField(
                default=True,
                help_text="Boolean indicating if the enterprise edition of Activiti is used",
                verbose_name="is enterprise",
            ),
        ),
        migrations.AlterField(
            model_name="activiticonfig",
            name="root_url",
            field=models.URLField(
                default="https://activiti.utrechtproeftuin.nl/activiti-app/api/",
                help_text="Root URL where activiti is installed. The REST api path is appended to this.",
                verbose_name="activiti root",
            ),
        ),
    ]
