# Generated by Django 2.2.9 on 2020-02-14 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activiti", "0003_auto_20200214_1109"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicetask",
            name="error_description",
            field=models.CharField(
                blank=True,
                help_text="Description of why the task failed",
                max_length=1000,
                verbose_name="error description",
            ),
        ),
    ]
