# Generated by Django 2.2.10 on 2020-02-20 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activiti", "0004_auto_20200220_1445"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicetask",
            name="execution_error",
            field=models.TextField(
                blank=True,
                help_text="The error that occurred during execution.",
                verbose_name="execution error",
            ),
        ),
    ]
